### ISSUE TITLE
运行的时候卡住了

### ISSUE THREAD

**Issue by 15523436188** [Hawaii-ol/arknights_minor_bypass#1]
b服的，用手机搭建了服务端，然后运行的时候出现了这个
Client TLS handshake failed. The client may not trust the proxy's certificate for dataflow.biliapi.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
证书是在运行过一遍后复制过去的，不知道出了什么问题，大佬能不能看下

**Comment by Hawaii-ol** [comment]
> b服的，用手机搭建了服务端，然后运行的时候出现了这个
> Client TLS handshake failed. The client may not trust the proxy's certificate for dataflow.biliapi.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
> 证书是在运行过一遍后复制过去的，不知道出了什么问题，大佬能不能看下

Android 7.0+默认不信任用户证书，抓包需要将mitmproxy的证书安装为系统证书
在安卓设置->安全->信任的凭据->系统列表中存在mitmproxy的证书才可以正常抓包。
安装系统证书需要root权限，建议在模拟器上执行，或者在真机中安装vmos等。不建议root真机，一是现在root的难度越来越大，二是安卓的安全政策越发缩紧，从Android 10.0起system分区被挂载为只读，root也没用，要装系统证书必须刷第三方Recovery。

**Comment by 15523436188** [comment]
> > b服的，用手机搭建了服务端，然后运行的时候出现了这个
> > Client TLS handshake failed. The client may not trust the proxy's certificate for dataflow.biliapi.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
> > 证书是在运行过一遍后复制过去的，不知道出了什么问题，大佬能不能看下
> 
> Android 7.0+默认不信任用户证书，抓包需要将mitmproxy的证书安装为系统证书
> 在安卓设置->安全->信任的凭据->系统列表中存在mitmproxy的证书才可以正常抓包。
> 安装系统证书需要root权限，建议在模拟器上执行，或者在真机中安装vmos等。不建议root真机，一是现在root的难度越来越大，二是安卓的安全政策越发缩紧，从Android 10.0起system分区被挂载为只读，root也没用，要装系统证书必须刷第三方Recovery。

意思就是要安装到跟目录里去吗？我已经信任它了

**Comment by Hawaii-ol** [comment]
我更新了README，可以看FAQ

**Comment by 15523436188** [comment]
> 我更新了README，可以看FAQ

没有certs文件夹怎么办？自己建立一个可以吗

**Comment by Hawaii-ol** [comment]
> > 我更新了README，可以看FAQ
> 
> 没有certs文件夹怎么办？自己建立一个可以吗

不好意思写错了，应该是cacerts目录，我更新一下

**Comment by 15523436188** [comment]
> > > 我更新了README，可以看FAQ
> > 
> > 
> > 没有certs文件夹怎么办？自己建立一个可以吗
> 
> 不好意思写错了，应该是cacerts目录，我更新一下

有了，但还是运行不了，问一下，这个是不是只能b站APP授权登录才行，是不是两部手机都连同一个热点或者WiFi才行？

**Comment by Hawaii-ol** [comment]
代理服务器和游戏客户端必须位于同一局域网下。账号密码登录要求代理服务器必须运行在Windows系统上。
其他登录不了的情况，可以把终端窗口中输出的log贴上来。

**Comment by 15523436188** [comment]
> 代理服务器和游戏客户端必须位于同一局域网下。账号密码登录要求代理服务器必须运行在Windows系统上。
> 其他登录不了的情况，可以把终端窗口中输出的log贴上来。
运行是这样的，然后卡在了授权界面
192.168.71.11:39570: Client TLS handshake failed. The client may not trust the proxy's certificate for app.bilibili.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
192.168.71.11:39570: client disconnect
192.168.71.11:39570: server disconnect app.bilibili.com:443 (122.246.9.8:443)

**Comment by Hawaii-ol** [comment]
> > 代理服务器和游戏客户端必须位于同一局域网下。账号密码登录要求代理服务器必须运行在Windows系统上。
> > 其他登录不了的情况，可以把终端窗口中输出的log贴上来。
> > 运行是这样的，然后卡在了授权界面
> > 192.168.71.11:39570: Client TLS handshake failed. The client may not trust the proxy's certificate for app.bilibili.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
> > 192.168.71.11:39570: client disconnect
> > 192.168.71.11:39570: server disconnect app.bilibili.com:443 (122.246.9.8:443)

你使用的安卓版本和b站客户端版本是什么？在浏览器中能否打开mitm.it这个页面？打开其他网页是否出现证书无效提示？脚本窗口中其他HTTPS连接是否有同样的错误提示？

**Comment by 15523436188** [comment]
> > > 代理服务器和游戏客户端必须位于同一局域网下。账号密码登录要求代理服务器必须运行在Windows系统上。
> > > 其他登录不了的情况，可以把终端窗口中输出的log贴上来。
> > > 运行是这样的，然后卡在了授权界面
> > > 192.168.71.11:39570: Client TLS handshake failed. The client may not trust the proxy's certificate for app.bilibili.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
> > > 192.168.71.11:39570: client disconnect
> > > 192.168.71.11:39570: server disconnect app.bilibili.com:443 (122.246.9.8:443)
> 
> 你使用的安卓版本和b站客户端版本是什么？在浏览器中能否打开mitm.it这个页面？打开其他网页有无证书无效提示？此时系统证书列表中是否存在mitmproxy？

安卓版本11，b站6.30.
浏览器打开mitm.it显示不通过If you can see this, traffic is not passing through mitmproxy.
Visit the Documentation
打开其他网页没有证书无效提示

**Comment by 15523436188** [comment]
> > > 代理服务器和游戏客户端必须位于同一局域网下。账号密码登录要求代理服务器必须运行在Windows系统上。
> > > 其他登录不了的情况，可以把终端窗口中输出的log贴上来。
> > > 运行是这样的，然后卡在了授权界面
> > > 192.168.71.11:39570: Client TLS handshake failed. The client may not trust the proxy's certificate for app.bilibili.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
> > > 192.168.71.11:39570: client disconnect
> > > 192.168.71.11:39570: server disconnect app.bilibili.com:443 (122.246.9.8:443)
> 
> 你使用的安卓版本和b站客户端版本是什么？在浏览器中能否打开mitm.it这个页面？打开其他网页有无证书无效提示？此时系统证书列表中是否存在mitmproxy？

系统证书列表用户列表里存在mitmproxy

**Comment by Hawaii-ol** [comment]
If you can see this, traffic is not passing through mitmproxy.
这说明你的客户端并没有走代理。请先在WLAN设置中正确配置代理，直到浏览器能够正常显示mitm.it这个页面

**Comment by 15523436188** [comment]
> If you can see this, traffic is not passing through mitmproxy.
> 这说明你的客户端并没有走代理。请先在WLAN设置中正确配置代理，直到浏览器能够正常显示mitm.it这个页面

第一次弄，不懂就问怎么配置……端口是8888，IP是啥😢192.1681.711？

**Comment by Hawaii-ol** [comment]
代理服务器主机填写运行破解脚本的电脑的IP地址。Windows可以用ipconfig /all查看，*nix可以用ifconfig -a查看。

**Comment by 15523436188** [comment]
> 代理服务器主机填写运行破解脚本的电脑的IP地址。Windows可以用ipconfig /all查看，*nix可以用ifconfig -a查看。

flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

rmnet_data2: flags=65<UP,RUNNING>  mtu 1500
        inet 10.7.43.108  netmask 255.255.255.248
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

tun0: flags=81<UP,POINTOPOINT,RUNNING>  mtu 9000
        inet 172.19.0.1  netmask 255.255.255.252  destination 172.19.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)

wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.6.54  netmask 255.255.255.0  broadcast 192.168.6.255
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 3000  (UNSPEC)

**Comment by Hawaii-ol** [comment]
> > 代理服务器主机填写运行破解脚本的电脑的IP地址。Windows可以用ipconfig /all查看，*nix可以用ifconfig -a查看。
> 
> flags=73<UP,LOOPBACK,RUNNING> mtu 65536
> inet 127.0.0.1 netmask 255.0.0.0
> unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> 
> rmnet_data2: flags=65<UP,RUNNING> mtu 1500
> inet 10.7.43.108 netmask 255.255.255.248
> unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> 
> tun0: flags=81<UP,POINTOPOINT,RUNNING> mtu 9000
> inet 172.19.0.1 netmask 255.255.255.252 destination 172.19.0.1
> unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 500 (UNSPEC)
> 
> wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
> inet 192.168.6.54 netmask 255.255.255.0 broadcast 192.168.6.255
> unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 3000 (UNSPEC)

如果你的服务器和客户端在同一机器上（真机和虚拟机不是同一机器），那么服务器IP填127.0.0.1，否则填192.168.6.54

**Comment by 15523436188** [comment]
> > > 代理服务器主机填写运行破解脚本的电脑的IP地址。Windows可以用ipconfig /all查看，*nix可以用ifconfig -a查看。
> > 
> > 
> > flags=73<UP,LOOPBACK,RUNNING> mtu 65536
> > inet 127.0.0.1 netmask 255.0.0.0
> > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> > rmnet_data2: flags=65<UP,RUNNING> mtu 1500
> > inet 10.7.43.108 netmask 255.255.255.248
> > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> > tun0: flags=81<UP,POINTOPOINT,RUNNING> mtu 9000
> > inet 172.19.0.1 netmask 255.255.255.252 destination 172.19.0.1
> > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 500 (UNSPEC)
> > wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
> > inet 192.168.6.54 netmask 255.255.255.0 broadcast 192.168.6.255
> > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 3000 (UNSPEC)
> 
> 如果你的服务器和客户端在同一机器上（真机和虚拟机不是同一机器），那么服务器IP填127.0.0.1，否则填192.168.6.54

emmmm直接网都连不上了，填了第二个，端口8888

**Comment by Hawaii-ol** [comment]
> > > > 代理服务器主机填写运行破解脚本的电脑的IP地址。Windows可以用ipconfig /all查看，*nix可以用ifconfig -a查看。
> > > 
> > > 
> > > flags=73<UP,LOOPBACK,RUNNING> mtu 65536
> > > inet 127.0.0.1 netmask 255.0.0.0
> > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> > > rmnet_data2: flags=65<UP,RUNNING> mtu 1500
> > > inet 10.7.43.108 netmask 255.255.255.248
> > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> > > tun0: flags=81<UP,POINTOPOINT,RUNNING> mtu 9000
> > > inet 172.19.0.1 netmask 255.255.255.252 destination 172.19.0.1
> > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 500 (UNSPEC)
> > > wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
> > > inet 192.168.6.54 netmask 255.255.255.0 broadcast 192.168.6.255
> > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 3000 (UNSPEC)
> > 
> > 
> > 如果你的服务器和客户端在同一机器上（真机和虚拟机不是同一机器），那么服务器IP填127.0.0.1，否则填192.168.6.54
> 
> emmmm直接网都连不上了，填了第二个，端口8888

网络配置相关的问题原则上和这个项目无关，我也不知道你所处网络的拓扑结构，无法判断问题出在哪。建议：
1.检查客户端能否ping通服务器
2.检查服务器上是否有相关防火墙策略，可以先暂时停止firewalld服务再尝试连接
3.如果可以，将客户端和服务器部署在同一机器上，走loopback，不受网络环境和防火墙影响。
直到能正常连接代理服务器并能显示mitm.it页面为止

**Comment by 15523436188** [comment]
> > > > > 代理服务器主机填写运行破解脚本的电脑的IP地址。Windows可以用ipconfig /all查看，*nix可以用ifconfig -a查看。
> > > > 
> > > > 
> > > > flags=73<UP,LOOPBACK,RUNNING> mtu 65536
> > > > inet 127.0.0.1 netmask 255.0.0.0
> > > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> > > > rmnet_data2: flags=65<UP,RUNNING> mtu 1500
> > > > inet 10.7.43.108 netmask 255.255.255.248
> > > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
> > > > tun0: flags=81<UP,POINTOPOINT,RUNNING> mtu 9000
> > > > inet 172.19.0.1 netmask 255.255.255.252 destination 172.19.0.1
> > > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 500 (UNSPEC)
> > > > wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
> > > > inet 192.168.6.54 netmask 255.255.255.0 broadcast 192.168.6.255
> > > > unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 3000 (UNSPEC)
> > > 
> > > 
> > > 如果你的服务器和客户端在同一机器上（真机和虚拟机不是同一机器），那么服务器IP填127.0.0.1，否则填192.168.6.54
> > 
> > 
> > emmmm直接网都连不上了，填了第二个，端口8888
> 
> 网络配置相关的问题原则上和这个项目无关，我也不知道你所处网络的拓扑结构，无法判断问题出在哪。建议：
> 1.检查客户端能否ping通服务器
> 2.检查服务器上是否有相关防火墙策略，可以先暂时停止firewalld服务再尝试连接
> 3.如果可以，将客户端和服务器部署在同一机器上，走loopback，不受网络环境和防火墙影响。
> 直到能正常连接代理服务器并能显示mitm.it页面为止

连了WiFi后输入192.168.43.114能够正常上网，能够显示mitm.it页面
开服务器的手机没有root
运转的时候还是会这样
192.168.43.11:40212: Client TLS handshake failed. The client may not trust the proxy's certificate for broadcast.chat.bilibili.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))
192.168.43.11:40212: client disconnect                            192.168.43.11:40212: server disconnect broadcast.chat.bilibili.com:7824 (110.43.50.80:7824)
GET http://112.80.128.33/gchatpic_new/4F79ACF6D96B0BDD…
                  << 206 Partial Content 8.49k
是不是因为服务端没有切换清华源的原因吗还是emmmm

**Comment by Hawaii-ol** [comment]
据我所知b站app并没有采用SSL pinning，因为我使用最新版6.41的b站app也可以正常捕获所有https流量。所以如果你出现了这个错误信息，说明客户端设备上要么没有成功安装mitmproxy的系统证书，要么没有走代理。
一个简单的自行验证方式：客户端浏览器访问`https://www.baidu.com`，应该正常显示百度首页，无证书问题，且服务端脚本窗口应该输出若干条类似`GET https://m.baidu.com/... 200 OK`的日志信息。如果：
1. 浏览器提示证书有问题，服务端同时输出若干条`Client TLS handshake failed. The client may not trust the proxy's certificate for m.baidu.com`的错误信息，则——你没有成功配置mitmproxy到系统证书中；
2. 浏览器正常显示百度首页，无证书问题，服务端无任何输出信息，则——你没有正确配置代理，浏览器是直接连接到百度服务器。

**Comment by 15523436188** [comment]
> 据我所知b站app并没有采用SSL pinning，因为我使用最新版6.41的b站app也可以正常捕获所有https流量。所以如果你出现了这个错误信息，说明客户端设备上要么没有成功安装mitmproxy的系统证书，要么没有走代理。
> 一个简单的自行验证方式：客户端浏览器访问`https://www.baidu.com`，应该正常显示百度首页，无证书问题，且服务端脚本窗口应该输出若干条类似`GET https://m.baidu.com/... 200 OK`的日志信息。如果：
> 
> 1. 浏览器提示证书有问题，服务端同时输出若干条`Client TLS handshake failed. The client may not trust the proxy's certificate for m.baidu.com`的错误信息，则——你没有成功配置mitmproxy到系统证书中；
> 2. 浏览器正常显示百度首页，无证书问题，服务端无任何输出信息，则——你没有正确配置代理，浏览器是直接连接到百度服务器。

是1，但是我安装到了系统目录了啊，，……不过是用户信任的，啊这，我再去试试，是要弄到系统证书里去对吧

**Comment by 15523436188** [comment]
> 据我所知b站app并没有采用SSL pinning，因为我使用最新版6.41的b站app也可以正常捕获所有https流量。所以如果你出现了这个错误信息，说明客户端设备上要么没有成功安装mitmproxy的系统证书，要么没有走代理。
> 一个简单的自行验证方式：客户端浏览器访问`https://www.baidu.com`，应该正常显示百度首页，无证书问题，且服务端脚本窗口应该输出若干条类似`GET https://m.baidu.com/... 200 OK`的日志信息。如果：
> 
> 1. 浏览器提示证书有问题，服务端同时输出若干条`Client TLS handshake failed. The client may not trust the proxy's certificate for m.baidu.com`的错误信息，则——你没有成功配置mitmproxy到系统证书中；
> 2. 浏览器正常显示百度首页，无证书问题，服务端无任何输出信息，则——你没有正确配置代理，浏览器是直接连接到百度服务器。

现在有个问题就是，不知道为什么保存不了mixporxy证书变成系统证书，每次复制之后放进去重启手机都没有系统证书在里面，怎么办

**Comment by Hawaii-ol** [comment]
> > 据我所知b站app并没有采用SSL pinning，因为我使用最新版6.41的b站app也可以正常捕获所有https流量。所以如果你出现了这个错误信息，说明客户端设备上要么没有成功安装mitmproxy的系统证书，要么没有走代理。
> > 一个简单的自行验证方式：客户端浏览器访问`https://www.baidu.com`，应该正常显示百度首页，无证书问题，且服务端脚本窗口应该输出若干条类似`GET https://m.baidu.com/... 200 OK`的日志信息。如果：
> > 
> > 1. 浏览器提示证书有问题，服务端同时输出若干条`Client TLS handshake failed. The client may not trust the proxy's certificate for m.baidu.com`的错误信息，则——你没有成功配置mitmproxy到系统证书中；
> > 2. 浏览器正常显示百度首页，无证书问题，服务端无任何输出信息，则——你没有正确配置代理，浏览器是直接连接到百度服务器。
> 
> 现在有个问题就是，不知道为什么保存不了mixporxy证书变成系统证书，每次复制之后放进去重启手机都没有系统证书在里面，怎么办

这就是为什么我一开始就不建议root真机。Android 11出厂即自带VAB(动态分区)，system分区被挂载为只读，即使root也无法写入，重启即会还原。如果你一定要在真机上操作，请自行搜索你的机型解锁system分区的方法。

**Comment by 15523436188** [comment]
> > > 据我所知b站app并没有采用SSL pinning，因为我使用最新版6.41的b站app也可以正常捕获所有https流量。所以如果你出现了这个错误信息，说明客户端设备上要么没有成功安装mitmproxy的系统证书，要么没有走代理。
> > > 一个简单的自行验证方式：客户端浏览器访问`https://www.baidu.com`，应该正常显示百度首页，无证书问题，且服务端脚本窗口应该输出若干条类似`GET https://m.baidu.com/... 200 OK`的日志信息。如果：
> > > 
> > > 1. 浏览器提示证书有问题，服务端同时输出若干条`Client TLS handshake failed. The client may not trust the proxy's certificate for m.baidu.com`的错误信息，则——你没有成功配置mitmproxy到系统证书中；
> > > 2. 浏览器正常显示百度首页，无证书问题，服务端无任何输出信息，则——你没有正确配置代理，浏览器是直接连接到百度服务器。
> > 
> > 
> > 现在有个问题就是，不知道为什么保存不了mixporxy证书变成系统证书，每次复制之后放进去重启手机都没有系统证书在里面，怎么办
> 
> 这就是为什么我一开始就不建议root真机。Android 11出厂即自带VAB(动态分区)，system分区被挂载为只读，即使root也无法写入，重启即会还原。如果你一定要在真机上操作，请自行搜索你的机型解锁system分区的方法。

我安装了另外一个文件的就是后缀为.pem的好像，然后成功弄成了系统文件然后签到，但是由于那天耽误了一天，现在是的松果皮肤是少一天才能领。然后我就用小黄鸟抓包了另外一个没有防沉迷的号的松果皮肤，想给他套上去。套是套的上，但是一使用的话就断开了，我都想请问一下，有没有什么办法能够让我保存那个松果皮肤。皮肤
