### ISSUE TITLE
大佬救我！

### ISSUE THREAD

**Issue by 15523436188** [Hawaii-ol/arknights_minor_bypass#2]
我安装了另外一个文件的就是后缀为.pem的证书，然后成功弄成了系统文件然后签到，但是由于那天耽误了一天，现在是的松果皮肤是少一天才能领。然后我就用小黄鸟抓包了另外一个没有防沉迷的号的松果皮肤，想给他套上去。套是套的上，但是一使用的话就断开了，我都想请问一下，有没有什么办法能够让我保存那个松果皮肤。

**Comment by Hawaii-ol** [comment]
签到接口是`https://ak-gs-gf.hypergryph.com/activity/getActivityCheckInReward`，可自行尝试，风险自负。这个issue已经偏离主题，因此我将关闭。

**Comment by 15523436188** [comment]
> 签到接口是`https://ak-gs-gf.hypergryph.com/activity/getActivityCheckInReward`，可自行尝试，风险自负。这个issue已经偏离主题，因此我将关闭。

这个是构建服务端后输入在termux里还是构建好服务端后在客服端使用？
