### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jeffhiei** [Hawaii-ol/arknights_minor_bypass#7]

**Comment by jeffhiei** [comment]
我不太会发图，求助一下大佬这应该怎么解决

**Comment by jeffhiei** [comment]
证书已经确认放进根目录了，wifi那也设置了代理端口8888

**Comment by jeffhiei** [comment]
没有选中cmd里的文本

**Comment by jeffhiei** [comment]
python版本3.9.6

**Comment by Hawaii-ol** [comment]
>Loading script scripts\bilibili_bypass.py
>Proxy server listening at http://*:8888

这两行文字说明服务器已成功启动并正在监听8888端口，接下来窗口中没有任何内容应该是你没有正确配置代理，流量并没有走mitmporxy代理服务器。
